# Generated by Django 5.2.6 on 2025-09-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
