# Generated by Django 5.2.6 on 2025-09-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_booking_seat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
    ]
