# Generated by Django 5.2.6 on 2025-09-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_no',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
